backend:
  name: github
  repo: Davao-IT-Solutions/Triple-Sun-Auto-Supply
site_url: https://www.triplesunautosupply.com
display_url: https://www.triplesunautosupply.com
local_backend: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_links: true

collections:
  - name: "parts"
    label: "Auto Parts"
    folder: "content/parts"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Summary", name: summary, widget: text, required: false}
      - {label: "Primary Image URL", name: "img_link", widget: "string", required: false, default: ""}
      - {label: "Cover Image URL", name: "img_link2", widget: "string", required: false, default: ""}
      - {label: "Third Image URL", name: "img_link3", widget: "string", required: false, default: ""}
      - {label: "Fourth Image URL", name: "img_link4", widget: "string", required: false, default: ""}
      - {label: 'Type', name: 'type', widget: 'select', options: ['engine', 'exterior', 'interior', 'wheels', 'batteries', 'drivetrain', 'grille'], required: true, default: "engine"}
      - {label: 'Status', name: 'status', widget: 'select', options: ['new', 'surplus'], required: true, default: "new"}
      - {label: "Price", name: "price", widget: "string", required: false}
      - {label: "Source Link", name: "source_link", widget: "string", required: false, default: ""}
      - {label: "Live Link", name: "live_link", widget: "string", required: false, default: ""}
      - {label: "Show on Homepage", name: "homepage", widget: "boolean", required: false, default: "false"}