backend:
  name: github
  repo: chesteralan/portfolio-nuxt-vuetifyjs
site_url: https://www.triplesunautosupply.com
display_url: https://www.triplesunautosupply.com
local_backend: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_links: false

collections:
  - name: "parts"
    label: "Auto Parts"
    folder: "content/parts"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Summary", name: summary, widget: text, required: false}
      - {label: "Source Link", name: "source_link", widget: "string", required: false, default: ""}
      - {label: "Image Link", name: "img_link", widget: "string", required: false, default: ""}
      - {label: "Live Link", name: "live_link", widget: "string", required: false, default: ""}
      - {label: 'Type', name: 'type', widget: 'select', options: ['engine', 'exterior', 'interior', 'wheels', 'batteries', 'drivetrain', 'grille'], required: true, default: ""}